# ~/.config/mpv/input.conf  (or %APPDATA%\mpv\input.conf on Windows)
# CTRL+LEFT  script-binding prev-file
# CTRL+RIGHT script-binding next-file
loop-file=inf
keep-open=yes
profile = high-quality	
scale = ewa_lanczossharp
mute=yes
sigmoid-upscaling = no
hdr-compute-peak = no
allow-delayed-peak-detect = yes
video-color-space=bt.709
video-color-primaries=bt.709
video-color-trc=bt.709
